# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sum_gaussians": "01_calibrate.ipynb",
         "fit_arc_lines2": "01_calibrate.ipynb",
         "OpenHSI": "02_capture.ipynb",
         "take_show": "02_capture.ipynb",
         "save": "03_data.ipynb",
         "Sensors": "06_sensors.ipynb"}

modules = ["calibrate.py",
           "capture.py",
           "data.py",
           "sensors.py"]

doc_url = "https://openhsi.github.io/openhsi"

git_url = "https://github.com/openhsi/docs/tree/master/"

def custom_doc_links(name): return None
